name: Build Docker Images

on:
  workflow_dispatch:
    inputs:
      frp-version:
        type: string
        required: true
        description: The frp version (see releases of frp project) to build the image for.

env:
  REGISTRY : ghcr.io
  IMAGE_NAME: chfoidl/frp

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frps:
    name: Build FRP Server Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # environment
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          repository: 'fatedier/frp'
          ref: ${{ github.event.inputs.message }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-server
          tags: ${{ github.event.inputs.frp-version }}

      - name: Build and push frps
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfiles/Dockerfile-for-frps
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  frpc:
    name: Build FRP Client
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # environment
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          repository: 'fatedier/frp'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-client
          tags: ${{ github.event.inputs.frp-version }}

      - name: Build and push frpc
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfiles/Dockerfile-for-frpc
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
